syntax = "proto3";

package imageupload.v1;

option go_package = "github.com/itsLeonB/stortr-protos/gen/go/imageupload/v1;imageupload";

message UploadStreamRequest {
  oneof data {
    Metadata metadata = 1;
    bytes chunk = 2;
  }
}

message Metadata {
  string content_type = 3;
  string filename = 4;
  int64 file_size = 5;
}

message UploadStreamResponse {
  string uri = 1;
}

message GetUrlRequest {
  string object_key = 1;
}

message GetUrlResponse {
  string url = 1;
}

message DeleteRequest {
  string object_key = 1;
}
